### PR TITLE
Modifications to Support ghidra 10.3

### PR DESCRIPTION
**Pull request by nstarke**
I had to get Kaiju running on Ghidra 10.3, so I thought I would share the modifications I made in order to get it all working.  Feel free to change anything to better suite your needs.  I'm not a java dev so forgive me.

### CODE REVIEW

**Comment by sei-gwassermann** [comment]
thank you for this! I made very similar changes to push today so will take a look and see if we can merge them.

**Comment by nstarke** [comment]
I will not be offended if you decide to discard these changes :-)

**Comment by sei-gwassermann** [comment]
I did make some additional changes, for example many of the help files were accidentally committed to git and were never meant to be there, that was part of the error. The help files should all be automatically generated at build time from markdown in the `docs/` directory, not static in the repo.

**Comment by sei-gwassermann** [comment]
Merged in #43 which does equivalent with some other tweaks, so I will close this one but thank you very much for sharing! I gave you a shoutout on #43 too.

**Pull request closed without merging**
