### PR TITLE
Update azure-pipelines.yml

### PR DESCRIPTION
**Pull request by sei-gwassermann**
update for latest build environment

### CODE REVIEW

**Comment by sei-gwassermann** [comment]
Seems to be some weird pipeline stuff going on not our fault? It says ghidra1015 succeeded here but on azure it says it failed for not finding z3 java bindings. but all the other ghidra versions did. huh.

**Comment by edmcman** [comment]
https://dev.azure.com/seipharos/kaiju/_build/results?buildId=1382&view=logs&j=9075884b-914e-5382-cd59-d37e24cdf20e&t=b946f259-9594-588f-dc92-661cec9b4dbe&l=58

```
  bad class file: /home/vsts/work/1/s/lib/com.microsoft.z3.jar(/com/microsoft/z3/Fixedpoint.class)
    class file has wrong version 61.0, should be 55.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.
```

**Comment by sei-gwassermann** [comment]
@edmcman why would it have a different classfile version than the others? presumably using the same z3 from cache?

**Comment by edmcman** [comment]
@sei-gwassermann I am looking... I suspect that it's taking the cached z3 directory from one of the Java 17 versions.

**Comment by edmcman** [comment]
I think what is happening is this:

One of the newer Ghidras that uses Java 17 is building z3 and caching the built directory.  This is then used by the Java 11 build, but ninja doesn't figure out that the Java version changes.

So try to add a `find .. -name '*.java' | xargs touch` right before calling `ninja` to see if that helps.

**Comment by edmcman** [comment]
Well, that didn't work.  I guess try `find .. -name '*.class' | xargs rm || true`

**Comment by edmcman** [comment]
Ok, how about `ninja clean`?  None of these things seem to be forcing the java files to be recompiled which is odd.

**Comment by edmcman** [comment]
Hmm.  Ok, I guess just delete the build directory entirely and see if that works.

**Comment by edmcman** [comment]
Looks like you need to add a || true, since the `build` dir may not exist if we aren't loading from cache.

**Pull request merged**
